# Generated by Django 3.2.3 on 2021-05-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_sku', models.SlugField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_descriptoin', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'PRODUCT',
            },
        ),
    ]
