# Generated by Django 3.2.3 on 2021-05-24 07:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_product_descriptoin_product_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.CharField(choices=[('PRODUCT_CREATE_EVENT', 'PRODUCT_CREATE_EVENT'), ('PRODUCT_UPDATE_EVENT', 'PRODUCT_UPDATE_EVENT')], max_length=100)),
                ('target_url', models.URLField(max_length=1000)),
            ],
            options={
                'db_table': 'WEBHOOK',
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_response', models.JSONField()),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.webhook')),
            ],
            options={
                'db_table': 'WEBHOOKLOG',
            },
        ),
    ]
