# Generated by Django 3.2.3 on 2021-05-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_webhook_webhooklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE')], default='SUCCESS', max_length=100),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='received_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
