# Generated by Django 3.2.3 on 2021-05-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210524_1339'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='PRODUCT',
        ),
        migrations.AlterModelTable(
            name='webhook',
            table='WEBHOOK',
        ),
        migrations.AlterModelTable(
            name='webhooklog',
            table='WEBHOOKLOG',
        ),
    ]
